version: '2'

services:
# Start messaging broker
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"

  # Start transformation worker
  strokewidthtransform:
    image: fsyanyong/open-ocr-preprocessor
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["114.114.114.114"]
    extra_hosts:
      - "image.jc.yzw.cn.qa:172.16.0.253"
      - "image.yzw.cn.qa:172.16.0.253"
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor stroke-width-transform"

  # Start OCR worker
  openocrworker:
    image: fsyanyong/${OPEN_OCR_INSTANCE}
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["114.114.114.114"]
    extra_hosts:
      - "image.jc.yzw.cn.qa:172.16.0.253"
      - "image.yzw.cn.qa:172.16.0.253"
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

  # Start http server
  openocr:
    image: fsyanyong/${OPEN_OCR_INSTANCE}
    volumes:
      - ./scripts/:/opt/open-ocr/
    ports:
      - "9292:9292"
    dns: ["114.114.114.114"]
    extra_hosts:
      - "image.jc.yzw.cn.qa:172.16.0.253"
      - "image.yzw.cn.qa:172.16.0.253"
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
